-- server/db_migrations/20251028_psl.sql
CREATE TABLE IF NOT EXISTS psl_drafts (
  ym CHAR(7) NOT NULL PRIMARY KEY,
  rows_json JSON NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS psl_saved (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  ym CHAR(7) NOT NULL,
  title VARCHAR(255) NOT NULL,
  rows_json JSON NOT NULL,
  totals_qty INT NOT NULL DEFAULT 0,
  totals_steril DECIMAL(10,2) NOT NULL DEFAULT 0,
  totals_ship DECIMAL(10,2) NOT NULL DEFAULT 0,
  totals_total DECIMAL(10,2) NOT NULL DEFAULT 0,
  pricePerPack DECIMAL(10,2) NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL,
  KEY (ym),
  KEY (createdAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
